Isaiasymanuel/verify phone number code
corecodeio/v202007 pull request #64
Opened 2020-08-26 19:54 UTC by pugaIsaias

Falta testear.

Hicimos 4 cosas:

1. Cree un `OnboardingCode.tsx` hace lo mismo que `onboarding`. Solo que llama a los métodos del API de `@CoreCodeIO/Librerias` correspondientes a la verificación del Código de Autorización.
2. Modifique el `InjectionKey` para que me permita implementar el `OnboardingCode` que se llama `OnboardingCodeInjectionKey`. 
3. Cambie el `VerifyPhoneNumberCode.tsx` para que sea como `SendPhoneNumberVerificationCode.tsx` solo que utilizando sus metodos del API y su nueva Injection Key. (Le falta poner en el comando del botón que cambie a la nueva Screen si es exitoso)
4. Se agrega un nuevo screen vacio `SetUpBussinessName.tsx` a donde se tiene que conectar el `VerifyPhoneNumberCode`.

2020-08-31 03:07 UTC, netpoe commented on native/src/feature/onboarding/model/OnboardingCode.ts
> +      result: queryResult.data?.valueOf() as Query["verifyPhoneNumberCode"],
De esto todavía tengo duda, tiene un smell, porque no debería existir este `as` si ya lo estás definiendo en el `useLazyQuery`. Qué pasa si utilizas: `Pick<Query, "verifyPhoneNumberCode">` en la definición de `useLazyQuery` ?

2020-08-31 03:08 UTC, netpoe commented on native/src/feature/onboarding/model/OnboardingCode.ts
> +      },
```suggestion
      executeVerifyPhoneNumberCode: async ({ input }) => {
        try {
        await execute({
          variables: {
            input,
          },
        });
        } catch (error) {
         // aquí manejamos posibles errores de networking y controlamos qué errores le llegan a la screen. 
        }
      },
```

2020-08-31 03:08 UTC, netpoe commented on native/src/feature/onboarding/model/OnboardingCode.ts
> +export class OnboardingCode {
No es necesario otro `model`, movamos la lógica de esta clase a `Onboarding`

2020-08-31 03:10 UTC, netpoe commented on native/src/feature/onboarding/screen/VerifyPhoneNumberCode.tsx
> +  };
Cuando sean valores que no se reasignan dentro del scope, usemos `const`. 

Por otro lado,  no es necesaria esta `const phoneNumber` ya que no hacemos nada con ella después:

```suggestion
  const onSetVerificationCode = (code: string) => {
    setInput({ input: { phoneNumber: args.input.phoneNumber, code } });
  };
```

2020-08-31 03:13 UTC, netpoe commented on native/src/feature/onboarding/screen/VerifyPhoneNumberCode.tsx
> +    queryResult: { error: VerifyPhoneNumberCodeError },
Este error lo puedes meter en un `React.useEffect`: 

```
React.useEffect(() => { 
if (!Boolean(verifyPhoneNumberCodeError)) {
return;
}

handleError();
}, [verifyPhoneNumberCodeError])
```

2020-08-31 03:15 UTC, netpoe commented on native/src/feature/onboarding/screen/VerifyPhoneNumberCode.tsx
> +      phoneNumber: "",
Este número ya debe de venir de los `params` de la navegación de la screen anterior.

2020-08-31 03:15 UTC, netpoe commented on native/src/feature/onboarding/screen/SetUpBussinessName.tsx
> +export const SetUpBussinessName: React.FC = () => (
```suggestion
export const SetBussinessName: React.FC = () => (
```

2020-08-31 03:16 UTC, netpoe commented on native/src/feature/onboarding/screen/SetUpBussinessName.tsx
> +export const SetUpBussinessName: React.FC = () => (
Aunque a la siguiente pantalla después de verificar podríamos llamarle: `ConnectStore`. Esto es para otro PR, quitemos esta screen por el momento.

2020-09-03 04:48 UTC, pugaIsaias commented
Hay unos errores de tsc, que cuando cambio el codigo en `components` `Text` e `Input` para quitarlo. 
Agregando las palabras que dan el error al `Layout`, y sus Clases padres en `Props`. Quita el error de tsc.
Pero ya no compila, alguna idea?

2020-09-07 04:44 UTC, netpoe commented on native/src/constant/theme.ts
> +    black: { main: "#000", dimmed: "rgba(0,0,0,0.5)" },
hay que buscar los `rgb` de los colores. También los de `main`

2020-09-07 04:44 UTC, netpoe commented on native/src/common/component/Link.tsx
> +  children: () => Promise<void>;
Esto no es una función, debe ser un `JSX.Element`. En realidad `children` viene por default en un `React.FC`, ya no hay que volverlo a declarar.

2020-09-07 18:52 UTC, pugaIsaias commented on native/src/constant/theme.ts
> +    black: { main: "#000", dimmed: "rgba(0,0,0,0.5)" },
ok listo

2020-09-07 18:58 UTC, pugaIsaias commented on native/src/common/component/Link.tsx
> +  children: () => Promise<void>;
De esta manera?

```
type Props = {
  url: string;
};

export const Link: React.FC<Props> = ({ url, children }) => {}
```

2020-09-07 20:42 UTC, pugaIsaias commented
@danbart  nos compartió esta librería para hacer el input de la primera screen mejor. 
[react-intl-tel-input](https://www.npmjs.com/package/react-intl-tel-input)
Pero aun no he podido implementarla correctamente.

2020-09-10 01:54 UTC, netpoe requested changes

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/screen/SendPhoneNumberVerificationCode.tsx
> +    console.log(phoneNumber);
Evitemos hacer push de `console.log`s

2020-09-10 01:54 UTC, netpoe commented on native/src/common/component/Link.tsx
> +  return (
Espacio entre `return` y el bloque anterior 👍

2020-09-10 01:54 UTC, netpoe commented on native/src/common/component/View.tsx
> +const width_windows = Dimensions.get("window").width;
En inglés correctamente es:

```suggestion
const windowWidth = Dimensions.get("window").width;
```

Pero podrías crear una constante `Layout.ts` en `src/constant` (que de hecho ya existe), que te de esos valores.

2020-09-10 01:54 UTC, netpoe commented on native/src/common/component/View.tsx
> +export const SecundaryView: React.FC<ViewProps & { container?: boolean }> = ({
```suggestion
export const SecondaryView: React.FC<ViewProps & { container?: boolean }> = ({
```

Aunque el nombre y la utilidad de estas constantes me parece un poco ambigua. 

Una `View` puede tener muchas utilidades. Con el progreso del desarrollo de la app te darás cuenta que van a existir varios tipos de `View`. 

Por lo tanto, utilicemos sólo un componente `View` sin clasificarlo por primario o secundario.

2020-09-10 01:54 UTC, netpoe commented on native/src/constant/theme.ts
> +      dimmed: "rgba(68, 69, 116,0.5)",
```suggestion
      dimmed: "rgba(68, 69, 116, 0.5)",
```

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/component/CodeInput.tsx
> +const CodeInput: React.FC<Props> = ({ onChangeText }) => {
Espacio entre estas líneas. y la constante : 

```suggestion
const CELL_COUNT = 6;

type Props = {
  onChangeText: (text: string) => void | undefined;
};

const CodeInput: React.FC<Props> = ({ onChangeText }) => {
```

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/component/CodeInput.tsx
> +      value={value}
```suggestion
      {...props}
      ref={ref}
      value={value}
```

Procura poner `props` al principio.

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/component/IntlTelInput.tsx
> +const PhoneNumberInput: React.FC<Props> = ({ onSetPhoneNumber }) => {
Que el nombre del file coincida con el nombre del componente.

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/component/IntlTelInput.tsx
> +    }
Código _oloroso_

Esta función no regresa nada y este syntax me parece raro. 

Si es un teléfono inválido, mejor mostremos un error debajo del input.

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/component/styles.ts
> +    borderColor: "#00000030",
Utilicemos colores del `theme`

Por otro lado, este `styles.ts` es poco escalable. Por eso existe `styled-syastem`. 

Eliminemos este archivo.

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/screen/VerifyPhoneNumberCode.tsx
> +    // navigation.navigate(OnboardingStackScreenName.VerifyPhoneNumberCode);
Evitemos código comentado.

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/screen/VerifyPhoneNumberCode.tsx
> +const loginURL = "https://google.com";
Este URL es inecesario.

2020-09-10 01:54 UTC, netpoe commented on native/src/feature/onboarding/screen/VerifyPhoneNumberCode.tsx
> +    </View>*/
momento de remover este bloque comentando. 
Evita subir código comentado o que no sirva.

2020-09-10 02:54 UTC, danbart commented on native/src/feature/onboarding/component/IntlTelInput.tsx
> +    }
es que pusimos una validación en la vista de des habilitar el botón si el numero era invalido, ahí se quedo así  por que isaias dijo que tenia como implementar los errores desde el controlador de las vistas. pero se me ocurre ahorita modificar una bandera que si es invalido este en false y si es valido en true y no ver si el numero trae algo o no trae nada.

2020-10-05 23:49 UTC, pugaIsaias commented
Currently working on verifyPhoneNumberCode-test

2020-10-05 23:49 UTC, closed without merging